services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ai_ticket_assistant
    ports:
      - "4000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/aiticketassistant
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: database
    ports:
      - "2717:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: {}