services:
  backend:
    build:
      context: ./ai-ticket-assistant
      dockerfile: ./Dockerfile
    container_name: ai-ticket-assistant
    ports:
      - "4000:3000"
    depends_on:
      - mongo
    volumes:
      - ./ai-ticket-assistant:/app
      - /app/node_modules
    env_file:
      - ./ai-ticket-assistant/.env
    restart: unless-stopped
  
  frontend:
    build:
      context: ./ai-ticket-platform
      dockerfile: ./Dockerfile
    container_name: ai-ticket-platform
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./ai-ticket-platform:/app
      - /app/node_modules
    env_file:
      -  ./ai-ticket-platform/.env
    
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: database
    ports:
      - "2717:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: {}